name: CI Tests

on:
  workflow_call:
    inputs:
      php:
        required: true
        type: number

jobs:
  test:
    runs-on: ubuntu-latest
    concurrency:
      group: ci-tests-php-${{ inputs.php }}
      cancel-in-progress: true

    env:
      extensions: parallel
      cache-key: extensions-cache-01

    steps:
    - uses: actions/checkout@v4

    - name: Setup cache environment
      id: extensions-cache
      uses: shivammathur/cache-extensions@v1
      with:
        php-version: ${{ inputs.php }}
        extensions: ${{ env.extensions }}
        key: ${{ env.cache-key }}

    - name: Cache extensions
      uses: actions/cache@v4
      with:
        path: ${{ steps.extensions-cache.outputs.dir }}
        key: ${{ steps.extensions-cache.outputs.key }}
        restore-keys: ${{ steps.extensions-cache.outputs.key }}

    - name: Install PHP ${{ inputs.php }} with ZTS
      uses: shivammathur/setup-php@v2
      env:
        phpts: ts
      with:
        php-version: ${{ inputs.php }}
        extensions: ${{ env.extensions }}
        ini-values: opcache.enable_cli=1, opcache.jit=tracing, opcache.jit_buffer_size=64M
        coverage: none

    - name: Install dependencies
      run: composer install --no-interaction --quiet

    - name: Execute tests
      run: ./vendor/bin/phpunit
      timeout-minutes: 1
