name: CI Tests on Linux with PHP 8.2

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  linux-php-8.0:
    uses: ./.github/workflows/ci-tests.yml
    with:
      os: ubuntu-latest
      php: 8.2
