name: CI Tests on Linux with PHP 8.0

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  linux_php_80:
    uses: ./.github/workflows/ci-tests.yml
    with:
      php: 8.0
