name: CI Tests on Linux with PHP 8.4

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  linux_php_84:
    uses: ./.github/workflows/ci-tests.yml
    with:
      php: 8.4
