name: CI Tests on Windows with PHP 8.1

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  windows_php_81:
    uses: ./.github/workflows/ci-tests.yml
    with:
      os: windows-latest
      php: 8.1
